version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    restart: on-failure
    container_name: api-posts
    volumes:
      - /app/node_modules 
      - ./server:/app 
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=postgres
      - DB_DATABASE=postgres
      - DB_PORT=5432